# services:
#   dialect_detector:
#     build: .
#     container_name: dialect_detector
#     ports:
#       - "3003:3003"
#     volumes:
#       - ../../audio-and-captions:/app/audio-and-captions
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: all
#               capabilities: [gpu]
#     restart: unless-stopped
#     networks:
#       - common_net

# networks:
#   common_net:
#     external: true

services:
  dialect_detector:
    build: .
    container_name: dialect_detector
    ports:
      - "3003:3003"
    volumes:
      - ../../audio-and-captions:/app/audio-and-captions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - common_net

networks:
  common_net:
    external: true
