services:
  dagster:
    image: dpipe
    container_name: dpipe
    build: .
    ports:
      - "3001:3001"
      - "4001:4000"
    volumes:
      - ./audio-and-captions:/app/audio-and-captions
      - ./keywords:/app/keywords
      - ./url_list:/app/url_list
      - ./proxies.json:/app/proxies.json
      - ./workspace.yaml:/app/workspace.yaml
      - ./config.yaml:/app/config.yaml
    environment:
      - DAGSTER_HOME=/app/dagster_home
      - DAGIT_HOST=0.0.0.0
      - DAGIT_PORT=3001
    command: ["dagster", "dev", "-w", "/app/workspace.yaml"]

  dpipe-mkdocs:
    image: squidfunk/mkdocs-material
    container_name: dpipe-mkdocs
    restart: always
    ports:
      - "0.0.0.0:5001:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
