site_name: dpipe
site_description: 'Website companion for dpipe'
site_author: 'Mohab Mostafa & Ibrahim Amin'
repo_url: 'https://github.com/MohabMostafa/TheCollector'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: green
      accent: black 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: green
      accent: black

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://github.com/MohabMostafa/TheCollector

copyright: |
  &copy; 2025 <a href="https://github.com/MohabMostafa/TheCollector"  target="_blank" rel="noopener">The Collector</a>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
- Getting started: index.md
- Installation: installation.md
- Features: features.md
- Reference: reference.md
- Examples: examples.md
